# Generated by Django 2.2.10 on 2020-02-20 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Sales', 'Sales'), ('Accounts', 'Accounts'), ('IT', 'IT')], default='Sales', max_length=100)),
                ('priority', models.CharField(choices=[('Very', 'Very High'), ('High', 'High'), ('Medium', 'Medium'), ('low', 'Low')], default='low', max_length=100)),
                ('status', models.CharField(choices=[('Newly logged', 'Newly logged'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Newly logged', max_length=100)),
                ('subject', models.CharField(blank=True, max_length=254)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('gps_coordinates', models.CharField(blank=True, max_length=30)),
                ('start_date', models.DateField(default=None, null=True)),
                ('end_date', models.DateField(default=None, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('logger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='logger')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='profile')),
            ],
        ),
    ]
