# Generated by Django 2.2.10 on 2020-02-20 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='gps_coordinates',
        ),
        migrations.CreateModel(
            name='TicketGeoLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Ticket', verbose_name='ticket')),
            ],
        ),
    ]
